CREATE TABLE IF NOT EXISTS "clinics"."cities" (
	"city_slug" text PRIMARY KEY NOT NULL,
	"city_name" text,
	"state" text,
	"meta_title" text,
	"meta_description" text,
	"h1" text,
	"h2" text,
	"sub_heading_text" text,
	"tick_1" text,
	"tick_2" text,
	"tick_3" text,
	"about_bookphysio" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "clinics"."clinics" (
	"long_name_version" text,
	"typeform_registration_link" text,
	"pms" text,
	"meta_title" text,
	"meta_description" text,
	"slug" text PRIMARY KEY NOT NULL,
	"website" text,
	"clinic_name" text,
	"display_on_web" text,
	"link_to_clinic_suburb_page" text,
	"full_address" text,
	"city" text,
	"suburb" text,
	"state" text,
	"postcode" integer,
	"email" text,
	"phone" text,
	"nearby1_txt" text,
	"nearby1_link" text,
	"nearby2_txt" text,
	"nearby2_link" text,
	"nearby3_txt" text,
	"nearby3_link" text,
	"nearby4_txt" text,
	"nearby4_link" text,
	"about_clinic" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "clinics"."suburbs" (
	"suburb_id" serial PRIMARY KEY NOT NULL,
	"suburb_slug" text,
	"suburb_name" text,
	"city" text,
	"state" text,
	"postcode" text,
	"meta_title" text,
	"meta_description" text,
	"h1" text,
	"h2" text,
	"about_bookphysio" text,
	"nearby1_link" text,
	"nearby1_txt" text,
	"nearby1_state" text,
	"nearby1_postcode" text,
	"nearby2_link" text,
	"nearby2_txt" text,
	"nearby2_state" text,
	"nearby2_postcode" text,
	"nearby3_link" text,
	"nearby3_txt" text,
	"nearby3_state" text,
	"nearby3_postcode" text,
	"nearby4_link" text,
	"nearby4_txt" text,
	"nearby4_state" text,
	"nearby4_postcode" text
);
